set_property IOSTANDARD LVCMOS33 [get_ports pin_usbp]
set_property IOSTANDARD LVCMOS33 [get_ports pin_usbn]
set_property IOSTANDARD LVCMOS33 [get_ports pin_sck]
set_property IOSTANDARD LVCMOS33 [get_ports pin_pu]
set_property IOSTANDARD LVCMOS33 [get_ports pin_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports pin_miso]
set_property IOSTANDARD LVCMOS33 [get_ports pin_led]
set_property IOSTANDARD LVCMOS33 [get_ports pin_cs]
set_property IOSTANDARD LVCMOS33 [get_ports pin_clk]
set_property PACKAGE_PIN L13 [get_ports pin_cs]
set_property PACKAGE_PIN E3 [get_ports pin_clk]
set_property PACKAGE_PIN T10 [get_ports pin_led]
set_property PACKAGE_PIN L16 [get_ports pin_sck]
set_property PACKAGE_PIN K18 [get_ports pin_miso]
set_property PACKAGE_PIN K17 [get_ports pin_mosi]
set_property PACKAGE_PIN U18 [get_ports pin_pu]
set_property PACKAGE_PIN R17 [get_ports pin_usbn]
set_property PACKAGE_PIN P17 [get_ports pin_usbp]


set_property BITSTREAM.CONFIG.CONFIGRATE 40 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
